version: '3'

services:
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=bootnode
    volumes:
      - bootnode-keys:/keys
    networks:
      primev_net:
        ipv4_address: 172.29.9.100

  provider:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bootnode
    environment:
      - NODE_TYPE=provider
    volumes:
      - provider-keys:/keys
    networks:
      - primev_net

  user:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bootnode
    environment:
      - NODE_TYPE=bidder
    volumes:
      - bidder-keys:/keys
    networks:
      - primev_net
    ports:
      - "13523:13523"
      - "13524:13524"

volumes:
  bootnode-keys:
  provider-keys:
  user-keys:

networks:
  primev_net:
    external: true
