version: '3'

services:
  bootnode:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: bootnode
    volumes:
      - ./integrationtest/keys/bootnode:/key
    depends_on:
      - funder
    networks:
      mev-int-net:
        ipv4_address: 172.29.0.2
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider1:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-1:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    depends_on:
      - provider-1
    environment:
      - PROVIDER_IP=provider-1:13524
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider2:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-2:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    depends_on:
      - provider-2
    environment:
      - PROVIDER_IP=provider-2:13524
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  provider-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: provider
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/provider3:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  provider-emulator-3:
    build:
      context: .
      dockerfile: ./integrationtest/provider/Dockerfile
    depends_on:
      - provider-3
    environment:
      - PROVIDER_IP=provider-3:13524
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-1:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user1:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-1:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    depends_on:
      - user-1
    environment:
      - USER_IP=user-1:13524
      - RPC_URL=http://34.215.163.180:8545
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-2:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user2:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-2:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    depends_on:
      - user-2
    environment:
      - USER_IP=user-2:13524
      - RPC_URL=http://34.215.163.180:8545
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-3:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user3:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-3:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    depends_on:
      - user-3
    environment:
      - USER_IP=user-3:13524
      - RPC_URL=http://34.215.163.180:8545
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-4:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user4:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-4:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    depends_on:
      - user-4
    environment:
      - USER_IP=user-4:13524
      - RPC_URL=http://34.215.163.180:8545
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  user-5:
    build:
      context: .
      dockerfile: ./integrationtest/Dockerfile
      args:
        node_type: user
    depends_on:
      - bootnode
    volumes:
      - ./integrationtest/keys/user5:/key
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:13523/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*",
              "go*",
              "libp2p*"
            ]
          }
        ]

  user-emulator-5:
    build:
      context: .
      dockerfile: ./integrationtest/user/Dockerfile
    depends_on:
      - user-5
    environment:
      - USER_IP=user-5:13524
      - RPC_URL=http://34.215.163.180:8545
    networks:
      - mev-int-net
    labels:
      com.datadoghq.ad.check_names: '["openmetrics"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics",
            "namespace": "integrationtest",
            "metrics": [
              "mev_commit*"
            ]
          }
        ]

  funder:
    build:
      context: ./integrationtest/foundry
    environment:
      - RPC_URL=http://34.215.163.180:8545
      - PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_KEY}
      - DD_TAGS=env:test
      - DD_SITE=datadoghq.com
    ports:
      - "5000:5000"
    networks:
      - mev-int-net

networks:
  mev-int-net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

