priv_key_file: /key
peer_type: user
p2p_port: 13522
http_port: 13523
rpc_port: 13524
secret: hello
log_fmt: text
log_level: debug
user_registry_contract: 0x322813Fd9A801c5507c9de605d63CEA4f2CE6c44
provider_registry_contract: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
rpc_endpoint: http://34.215.163.180:8545
bootnodes:
  - /ip4/172.29.0.2/tcp/13522/p2p/16Uiu2HAmLYUvthfDCewNMdfPhrVefBbsfaPL22fWWfC2zuoh5SpV
