swagger: "2.0"
info:
  title: Builder API
  version: 1.0.0-alpha
  license:
    name: Business Source License 1.1
    url: https://github.com/primevprotocol/mev-commit/blob/main/LICENSE
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/builder/receive_bids:
    get:
      summary: ReceiveBids
      description: |-
        ReceiveBids is called by the builder to receive bids from the mev-commit node.
        The mev-commit node will stream bids to the builder as the response.
      operationId: Builder_ReceiveBids
      responses:
        "200":
          description: A successful response.(streaming responses)
          schema:
            type: object
            properties:
              result:
                $ref: '#/definitions/rpcbuilderapiv1Bid'
              error:
                $ref: '#/definitions/googlerpcStatus'
            title: Stream result of rpcbuilderapiv1Bid
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
  /v1/builder/send_processed_bids:
    post:
      summary: SendProcessedBids
      description: |-
        SendProcessedBids is called by the builder to send processed bids to the mev-commit node.
        The builder will stream processed bids to the mev-commit node.
      operationId: Builder_SendProcessedBids
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1EmptyMessage'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/googlerpcStatus'
      parameters:
        - name: body
          description: Response sent by the builder with the decision on the bid received. (streaming inputs)
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1BidResponse'
definitions:
  googlerpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcbuilderapiv1Bid:
    type: object
    example:
      bid_amount: 1e+18
      bid_digest: 9dJinwL+FZ6B1xsIQQo8t8B0ZXJubJwY86l/Yu7yAH159QrPHU0qj2P+YFj+llbuI1ZygdxGsX8+P3byMEA5ig==
      block_number: 123456
      tx_hash: 91a89B633194c0D86C539A1A5B14DCCacfD47094
    properties:
      txHash:
        type: string
        description: Hex string encoding of the hash of the transaction that the user wants to include in the block.
        pattern: '[a-fA-F0-9]{40}'
      bidAmount:
        type: string
        format: int64
        description: Amount of ETH that the user is willing to pay to the builder for including the transaction in the block.
      blockNumber:
        type: string
        format: int64
        description: Max block number that the user wants to include the transaction in.
      bidDigest:
        type: string
        format: byte
        description: Digest of the bid message signed by the user.
    description: Signed bid message from users to the builder.
    title: Bid message
    required:
      - txHash
      - bidAmount
      - blockNumber
      - bidDigest
  v1BidResponse:
    type: object
    example:
      bid_digest: 9dJinwL+FZ6B1xsIQQo8t8B0ZXJubJwY86l/Yu7yAH159QrPHU0qj2P+YFj+llbuI1ZygdxGsX8+P3byMEA5ig==
      status: STATUS_ACCEPTED
    properties:
      bidDigest:
        type: string
        format: byte
        description: Digest of the bid message signed by the user.
      status:
        $ref: '#/definitions/v1BidResponseStatus'
        description: Status of the bid.
    description: Response sent by the builder with the decision on the bid received.
    title: Bid response
    required:
      - bidDigest
      - status
  v1BidResponseStatus:
    type: string
    enum:
      - STATUS_ACCEPTED
      - STATUS_REJECTED
  v1EmptyMessage:
    type: object
